const express = require("express");
const mechApp = express();
const bodyParser = require("body-parser");
const loadRouter = require("../routes/load.routes");
const userRouter = require("../routes/user.routes");
const routes = require("../helpers/route_consts");
mechApp.use(bodyParser.json());
mechApp.use(routes.loadBaseRoutes, loadRouter);
mechApp.use(routes.userBaseRoutes, userRouter);
module.exports = mechApp;
